version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "${PORT:-3000}:3000" # Use PORT environment variable or default to 3000
    depends_on:
      - mongodb
    environment:
      - DB_URL=mongodb://mongodb:27017/grocery # MongoDB connection URL

volumes:
  mongodb_data:
